name: module-storage-account
concurrency: module-storage-account

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'modules/storage-account/**'

env:
  MODULE_NAME: storage-account
  MODULE_REGISTRY_SERVER: cshaightoys.azurecr.io
  MODULE_FILE_PATH: modules/storage-account/main.bicep
  MODULE_METADATA_FILE_PATH: modules/storage-account/metadata.json

jobs:
  lint:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Bicep linter
        run: az bicep build --file ${{ env.MODULE_FILE_PATH }}

  publish:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get module version number
        run: |
          majorMinorVersionNumber=$(jq '(.version.major | tostring) + "." + (.version.minor | tostring)' ${{ env.MODULE_METADATA_FILE_PATH }} --raw-output)
          versionNumber="$majorMinorVersionNumber.${{ github.run_number }}"
          echo "MODULE_VERSION=$versionNumber" >> $GITHUB_ENV

      - name: Publish module
        uses: azure/cli@v1
        with:
          inlineScript: |
            az bicep install
            az bicep publish \
              --target 'br:${{ env.MODULE_REGISTRY_SERVER }}/${{ env.MODULE_NAME }}:${{ env.MODULE_VERSION }}' \
              --file ${{ env.MODULE_FILE_PATH }}
              