name: template-spec-linux-app-service
concurrency: template-spec-linux-app-service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'template-specs/linux-app-service/**'

env:
  AZURE_RESOURCEGROUP_NAME: ToyReusable
  AZURE_REGION: westus3
  TEMPLATE_SPEC_NAME: linux-app-service
  TEMPLATE_SPEC_FILE_PATH: template-specs/linux-app-service/main.bicep

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Bicep linter
        run: az bicep build --file ${{ env.TEMPLATE_SPEC_FILE_PATH }}

  publish:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Publish template spec
        uses: azure/cli@v1
        with:
          inlineScript: |
            az ts create \
              --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
              --name ${{ env.TEMPLATE_SPEC_NAME }} \
              --version ${{ github.run_number }} \
              --template-file ${{ env.TEMPLATE_SPEC_FILE_PATH }} \
              --location ${{ env.AZURE_REGION }} \
              --yes
